version: '3'
services:
  db:
     image: mysql:5.7
     ports:
      - 4306:3306
     volumes:
       - db-volume:/var/lib/mysql
     environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_HOST=127.0.0.1
  web:
     build: .
     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
     volumes:
       - .:/myapp
       - .:/rspec_sample
     ports:
       - "3000:3000"
     depends_on:
       - db
     tty: true
     stdin_open: true
volumes:
   db-volume:

